micronaut:
    application:
        name: sync-commit

kafka:
    bootstrap.servers: localhost:50702
    consumers:
        default:
            group-id: sync-commit
            auto.offset.reset: earliest
